import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { FileText, Wallet, GitBranch, Shield } from "lucide-react";
const Index = () => {
    return (_jsx("div", { className: "min-h-screen bg-background", children: _jsxs("div", { className: "container mx-auto px-4 py-8", children: [_jsxs("header", { className: "mb-12 text-center", children: [_jsx("h1", { className: "text-4xl font-bold mb-4 text-foreground", children: "BitMind Smart Invoice Dashboard" }), _jsx("p", { className: "text-muted-foreground text-lg", children: "AI-powered invoice escrow for DAOs on Stacks blockchain" })] }), _jsxs("div", { className: "grid md:grid-cols-2 lg:grid-cols-4 gap-6 mb-12", children: [_jsxs(Card, { children: [_jsxs(CardHeader, { children: [_jsx(FileText, { className: "w-8 h-8 mb-2 text-primary" }), _jsx(CardTitle, { children: "Active Invoices" }), _jsx(CardDescription, { children: "Current ongoing deals" })] }), _jsx(CardContent, { children: _jsx("p", { className: "text-3xl font-bold", children: "12" }) })] }), _jsxs(Card, { children: [_jsxs(CardHeader, { children: [_jsx(Wallet, { className: "w-8 h-8 mb-2 text-primary" }), _jsx(CardTitle, { children: "Total Value" }), _jsx(CardDescription, { children: "Locked in escrow" })] }), _jsx(CardContent, { children: _jsx("p", { className: "text-3xl font-bold", children: "$45.2K" }) })] }), _jsxs(Card, { children: [_jsxs(CardHeader, { children: [_jsx(GitBranch, { className: "w-8 h-8 mb-2 text-primary" }), _jsx(CardTitle, { children: "Milestones" }), _jsx(CardDescription, { children: "Completed this month" })] }), _jsx(CardContent, { children: _jsx("p", { className: "text-3xl font-bold", children: "24" }) })] }), _jsxs(Card, { children: [_jsxs(CardHeader, { children: [_jsx(Shield, { className: "w-8 h-8 mb-2 text-primary" }), _jsx(CardTitle, { children: "Disputes" }), _jsx(CardDescription, { children: "Currently active" })] }), _jsx(CardContent, { children: _jsx("p", { className: "text-3xl font-bold", children: "2" }) })] })] }), _jsxs(Card, { className: "mb-8", children: [_jsxs(CardHeader, { children: [_jsx(CardTitle, { children: "Recent Invoices" }), _jsx(CardDescription, { children: "Your latest invoice activities" })] }), _jsx(CardContent, { children: _jsx("div", { className: "space-y-4", children: [
                                    { id: "INV-001", status: "funded", amount: "$12,500", dao: "DeFi DAO" },
                                    { id: "INV-002", status: "pending", amount: "$8,300", dao: "NFT Collective" },
                                    { id: "INV-003", status: "completed", amount: "$15,000", dao: "Web3 Guild" },
                                ].map((invoice) => (_jsxs("div", { className: "flex items-center justify-between p-4 border border-border rounded-lg", children: [_jsxs("div", { className: "flex items-center gap-4", children: [_jsx(FileText, { className: "w-6 h-6 text-muted-foreground" }), _jsxs("div", { children: [_jsx("p", { className: "font-semibold", children: invoice.id }), _jsx("p", { className: "text-sm text-muted-foreground", children: invoice.dao })] })] }), _jsxs("div", { className: "flex items-center gap-4", children: [_jsx("p", { className: "font-semibold", children: invoice.amount }), _jsx(Badge, { variant: invoice.status === "completed"
                                                        ? "default"
                                                        : invoice.status === "funded"
                                                            ? "secondary"
                                                            : "outline", children: invoice.status }), _jsx(Button, { size: "sm", children: "View" })] })] }, invoice.id))) }) })] })] }) }));
};
export default Index;
